// Code generated by runnerq-spec tools/gen from schema/postgres. DO NOT EDIT.

package spec

// PostgresMigration is one schema migration. Every migration is safe to
// re-run; they run in order, in one transaction.
type PostgresMigration struct {
	Name string
	SQL  string
}

// PostgresConcurrentIndex is built with CREATE INDEX CONCURRENTLY after the
// migrations, outside any transaction: drop it if invalid, build it if
// missing, then drop Replaces.
type PostgresConcurrentIndex struct {
	Name     string
	Table    string
	Replaces string
	SQL      string
}

// CatalogColumn is a column as information_schema reports it. Default is ""
// when the column has none.
type CatalogColumn struct {
	Name     string
	Type     string
	Nullable bool
	Default  string
}

// CatalogTable is a table, its columns and its primary key.
type CatalogTable struct {
	Name       string
	Columns    []CatalogColumn
	PrimaryKey []string
}

// CatalogIndex is an index other than a primary key, as pg_get_indexdef
// renders it without the schema.
type CatalogIndex struct {
	Name       string
	Table      string
	Definition string
}

// Catalog is what the migrations and concurrent indexes produce. Retired
// objects must not exist.
type Catalog struct {
	Tables         []CatalogTable
	Indexes        []CatalogIndex
	RetiredColumns []string // table.column
	RetiredIndexes []string
}

// PostgresMigrations run in order.
var PostgresMigrations = []PostgresMigration{
	{Name: "0001_baseline", SQL: `-- Activities table (permanent - no TTL)
CREATE TABLE IF NOT EXISTS runnerq_activities (
    id UUID PRIMARY KEY,
    queue_name TEXT NOT NULL,
    activity_type TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    scheduled_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    lease_deadline_ms BIGINT,
    current_worker_id TEXT,
    last_worker_id TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 0,
    timeout_seconds BIGINT NOT NULL DEFAULT 300,
    retry_delay_seconds BIGINT NOT NULL DEFAULT 60,
    max_retry_delay_seconds BIGINT NOT NULL DEFAULT 0,
    last_error TEXT,
    last_error_at TIMESTAMPTZ,
    metadata JSONB,
    idempotency_key TEXT
);

-- Inputs, apart from the activity rows that claims, leases and status
-- changes rewrite: an activity's payload is written once and read when it is
-- claimed or inspected. serialization names the payload's encoding
-- ('json-v1': plain JSON, the only one Go writes; the TypeScript SDK also
-- writes 'superjson-v1').
CREATE TABLE IF NOT EXISTS runnerq_inputs (
    activity_id UUID PRIMARY KEY,
    queue_name TEXT NOT NULL,
    payload JSONB NOT NULL,
    serialization TEXT NOT NULL DEFAULT 'json-v1'
);

-- Migration: payloads used to live in runnerq_activities.payload. Move them
-- into runnerq_inputs and drop the column, in the schema transaction, so a
-- database is either wholly before or wholly after the move. Processes on
-- an older version of this SDK can't use the database afterwards: stop them
-- before starting this one.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND table_name = 'runnerq_activities' AND column_name = 'payload') THEN
        INSERT INTO runnerq_inputs (activity_id, queue_name, payload)
            SELECT id, queue_name, payload FROM runnerq_activities
            ON CONFLICT (activity_id) DO NOTHING;
        ALTER TABLE runnerq_activities DROP COLUMN payload;
        ALTER TABLE runnerq_activities ALTER COLUMN max_retries SET DEFAULT 0;
    END IF;
END $$;

-- Indexes for efficient queries
--
-- NOTE: the hot dequeue indexes (idx_runnerq_dequeue_effective_v2,
-- idx_runnerq_dequeue_order_v2) and the query indexes are NOT created here:
-- see concurrent_indexes.json. A plain CREATE INDEX takes a SHARE lock that
-- blocks all writes on runnerq_activities for the duration of the build; at
-- boot, on a hot queue, that stalls every enqueue/dequeue/ack in the cluster.
CREATE INDEX IF NOT EXISTS idx_runnerq_activities_processing
    ON runnerq_activities(queue_name, lease_deadline_ms)
    WHERE status = 'processing';
CREATE INDEX IF NOT EXISTS idx_runnerq_completed_non_cron
    ON runnerq_activities(queue_name, completed_at DESC, created_at DESC)
    WHERE status IN ('completed', 'failed')
      AND (metadata->>'source') IS DISTINCT FROM 'cron';
CREATE INDEX IF NOT EXISTS idx_runnerq_completed_cron
    ON runnerq_activities(queue_name, completed_at DESC, created_at DESC)
    WHERE status IN ('completed', 'failed')
      AND metadata->>'source' = 'cron';
CREATE INDEX IF NOT EXISTS idx_runnerq_dead_letter
    ON runnerq_activities(queue_name, completed_at DESC)
    WHERE status = 'dead_letter';

-- Migration: add column for existing deployments (idempotent, metadata-only on PG 11+).
ALTER TABLE runnerq_activities
    ADD COLUMN IF NOT EXISTS max_retry_delay_seconds BIGINT NOT NULL DEFAULT 0;

-- Lineage columns for parent/child activity tracking.
ALTER TABLE runnerq_activities
    ADD COLUMN IF NOT EXISTS parent_activity_id UUID,
    ADD COLUMN IF NOT EXISTS root_activity_id UUID,
    ADD COLUMN IF NOT EXISTS depth SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS waiting_result_id UUID;

CREATE INDEX IF NOT EXISTS idx_runnerq_parent_id
    ON runnerq_activities(parent_activity_id)
    WHERE parent_activity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_runnerq_root_id
    ON runnerq_activities(root_activity_id)
    WHERE root_activity_id IS NOT NULL;
-- Partial index for the workflows-list view (parent IS NULL = roots only),
-- ordered for the typical "newest first" query.
CREATE INDEX IF NOT EXISTS idx_runnerq_root_only
    ON runnerq_activities(queue_name, created_at DESC)
    WHERE parent_activity_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_runnerq_root_status
    ON runnerq_activities(queue_name, status)
    WHERE parent_activity_id IS NULL;

-- Idempotency keys table
CREATE TABLE IF NOT EXISTS runnerq_idempotency (
    queue_name TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    activity_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (queue_name, idempotency_key)
);

-- Events table (permanent - full history)
CREATE TABLE IF NOT EXISTS runnerq_events (
    id BIGSERIAL PRIMARY KEY,
    activity_id UUID NOT NULL,
    queue_name TEXT NOT NULL,
    event_type TEXT NOT NULL,
    worker_id TEXT,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_runnerq_events_activity
    ON runnerq_events(activity_id, created_at DESC);
-- Cursor tailing for the live event stream (EventStream reads id > cursor).
CREATE INDEX IF NOT EXISTS idx_runnerq_events_queue_seq
    ON runnerq_events(queue_name, id);

-- Results table. Rows live until the retention sweeper deletes their
-- workflow tree (or forever when retention is not configured).
CREATE TABLE IF NOT EXISTS runnerq_results (
    activity_id UUID PRIMARY KEY,
    queue_name TEXT NOT NULL,
    state TEXT NOT NULL,
    data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- owner_activity_id ties every result row to the activity whose lifetime
-- governs it. For normal activity results it equals activity_id; for Run/
-- Sleep checkpoints (whose activity_id is a synthetic UUIDv5 matching no
-- activity row) it is the handler's activity — without it, checkpoint rows
-- could never be garbage-collected. NULL on legacy rows (never swept).
ALTER TABLE runnerq_results
    ADD COLUMN IF NOT EXISTS owner_activity_id UUID;
CREATE INDEX IF NOT EXISTS idx_runnerq_results_owner
    ON runnerq_results(queue_name, owner_activity_id)
    WHERE owner_activity_id IS NOT NULL;

-- step is the human identity of a checkpoint row, "kind:name" (e.g.
-- "run:create-transfer", "sleep:retry-backoff") — the same string the checkpoint
-- ID is derived from, persisted so the console can show a workflow's durable
-- step history (the checkpoint ID itself is a one-way hash). NULL for an
-- activity's own final result and for legacy rows. No dedicated index: read only
-- by owner (already indexed above) on the console path, never on a hot path.
ALTER TABLE runnerq_results
    ADD COLUMN IF NOT EXISTS step TEXT;

-- serialization names the result data's encoding, as for inputs.
ALTER TABLE runnerq_results
    ADD COLUMN IF NOT EXISTS serialization TEXT NOT NULL DEFAULT 'json-v1';

-- Retention sweep: find roots that have been terminal longer than the TTL.
CREATE INDEX IF NOT EXISTS idx_runnerq_root_terminal_age
    ON runnerq_activities(queue_name, status, completed_at)
    WHERE parent_activity_id IS NULL
      AND status IN ('completed', 'failed', 'dead_letter');

-- Worker pools: one row per live engine instance. Heartbeats let us tell
-- which pools are still alive for cluster-wide capacity reporting.
CREATE TABLE IF NOT EXISTS runnerq_worker_pools (
    pool_id        UUID PRIMARY KEY,
    queue_name     TEXT NOT NULL,
    max_workers    INTEGER NOT NULL,
    activity_types TEXT[],
    started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_runnerq_worker_pools_queue_alive
    ON runnerq_worker_pools(queue_name, last_seen_at);

-- Command ledger: applied RunnerQ Cloud commands and their results, so a
-- repeated command_id replays its result instead of applying twice. Rows are
-- pruned after a week (commands must be replayable for at least 24 hours).
CREATE TABLE IF NOT EXISTS runnerq_commands (
    queue_name  TEXT NOT NULL,
    command_id  TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    kind        TEXT NOT NULL,
    result      JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (queue_name, command_id)
);
CREATE INDEX IF NOT EXISTS idx_runnerq_commands_created
    ON runnerq_commands(created_at);

-- Durable references survive handler replay and are removed with consumer trees.
CREATE TABLE IF NOT EXISTS runnerq_dependencies (
 queue_name TEXT NOT NULL,
 waiter_activity_id UUID NOT NULL,
 result_id UUID NOT NULL,
 producer_activity_id UUID,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 PRIMARY KEY (queue_name, waiter_activity_id, result_id)
);
CREATE INDEX IF NOT EXISTS idx_runnerq_dependencies_result
 ON runnerq_dependencies(queue_name, result_id);
CREATE INDEX IF NOT EXISTS idx_runnerq_dependencies_producer
 ON runnerq_dependencies(queue_name, producer_activity_id);
`},
}

// PostgresConcurrentIndexes are built in order after the migrations.
var PostgresConcurrentIndexes = []PostgresConcurrentIndex{
	{Name: "idx_runnerq_dequeue_effective_v2", Table: "runnerq_activities", Replaces: "idx_runnerq_dequeue_effective", SQL: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_runnerq_dequeue_effective_v2
ON runnerq_activities (
    queue_name,
    activity_type,
    priority DESC,
    retry_count DESC,
    COALESCE(scheduled_at, created_at) ASC
)
WHERE status IN ('pending', 'scheduled', 'retrying', 'waiting')`},
	{Name: "idx_runnerq_dequeue_order_v2", Table: "runnerq_activities", Replaces: "idx_runnerq_dequeue_order", SQL: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_runnerq_dequeue_order_v2
ON runnerq_activities (
    queue_name,
    priority DESC,
    retry_count DESC,
    COALESCE(scheduled_at, created_at) ASC
)
WHERE status IN ('pending', 'scheduled', 'retrying', 'waiting')`},
	{Name: "idx_runnerq_query_created", Table: "runnerq_activities", Replaces: "", SQL: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_runnerq_query_created
ON runnerq_activities (created_at DESC, id DESC)`},
	{Name: "idx_runnerq_query_status_created", Table: "runnerq_activities", Replaces: "", SQL: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_runnerq_query_status_created
ON runnerq_activities (status, created_at DESC, id DESC)`},
	{Name: "idx_runnerq_query_type_created", Table: "runnerq_activities", Replaces: "", SQL: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_runnerq_query_type_created
ON runnerq_activities (activity_type, created_at DESC, id DESC)`},
}

// PostgresCatalog is schema/postgres/catalog.json.
var PostgresCatalog = Catalog{
	Tables: []CatalogTable{
		{Name: "runnerq_activities", PrimaryKey: []string{"id"}, Columns: []CatalogColumn{
			{Name: "activity_type", Type: "text", Nullable: false, Default: ""},
			{Name: "completed_at", Type: "timestamptz", Nullable: true, Default: ""},
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "current_worker_id", Type: "text", Nullable: true, Default: ""},
			{Name: "depth", Type: "int2", Nullable: false, Default: "0"},
			{Name: "id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "idempotency_key", Type: "text", Nullable: true, Default: ""},
			{Name: "last_error", Type: "text", Nullable: true, Default: ""},
			{Name: "last_error_at", Type: "timestamptz", Nullable: true, Default: ""},
			{Name: "last_worker_id", Type: "text", Nullable: true, Default: ""},
			{Name: "lease_deadline_ms", Type: "int8", Nullable: true, Default: ""},
			{Name: "max_retries", Type: "int4", Nullable: false, Default: "0"},
			{Name: "max_retry_delay_seconds", Type: "int8", Nullable: false, Default: "0"},
			{Name: "metadata", Type: "jsonb", Nullable: true, Default: ""},
			{Name: "parent_activity_id", Type: "uuid", Nullable: true, Default: ""},
			{Name: "priority", Type: "int4", Nullable: false, Default: "1"},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "retry_count", Type: "int4", Nullable: false, Default: "0"},
			{Name: "retry_delay_seconds", Type: "int8", Nullable: false, Default: "60"},
			{Name: "root_activity_id", Type: "uuid", Nullable: true, Default: ""},
			{Name: "scheduled_at", Type: "timestamptz", Nullable: true, Default: ""},
			{Name: "started_at", Type: "timestamptz", Nullable: true, Default: ""},
			{Name: "status", Type: "text", Nullable: false, Default: "'pending'::text"},
			{Name: "timeout_seconds", Type: "int8", Nullable: false, Default: "300"},
			{Name: "waiting_result_id", Type: "uuid", Nullable: true, Default: ""},
		}},
		{Name: "runnerq_commands", PrimaryKey: []string{"queue_name", "command_id"}, Columns: []CatalogColumn{
			{Name: "command_id", Type: "text", Nullable: false, Default: ""},
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "fingerprint", Type: "text", Nullable: false, Default: ""},
			{Name: "kind", Type: "text", Nullable: false, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "result", Type: "jsonb", Nullable: false, Default: ""},
		}},
		{Name: "runnerq_dependencies", PrimaryKey: []string{"queue_name", "waiter_activity_id", "result_id"}, Columns: []CatalogColumn{
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "producer_activity_id", Type: "uuid", Nullable: true, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "result_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "waiter_activity_id", Type: "uuid", Nullable: false, Default: ""},
		}},
		{Name: "runnerq_events", PrimaryKey: []string{"id"}, Columns: []CatalogColumn{
			{Name: "activity_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "detail", Type: "jsonb", Nullable: true, Default: ""},
			{Name: "event_type", Type: "text", Nullable: false, Default: ""},
			{Name: "id", Type: "int8", Nullable: false, Default: "nextval('runnerq_events_id_seq'::regclass)"},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "worker_id", Type: "text", Nullable: true, Default: ""},
		}},
		{Name: "runnerq_idempotency", PrimaryKey: []string{"queue_name", "idempotency_key"}, Columns: []CatalogColumn{
			{Name: "activity_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "idempotency_key", Type: "text", Nullable: false, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "updated_at", Type: "timestamptz", Nullable: false, Default: "now()"},
		}},
		{Name: "runnerq_inputs", PrimaryKey: []string{"activity_id"}, Columns: []CatalogColumn{
			{Name: "activity_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "payload", Type: "jsonb", Nullable: false, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "serialization", Type: "text", Nullable: false, Default: "'json-v1'::text"},
		}},
		{Name: "runnerq_results", PrimaryKey: []string{"activity_id"}, Columns: []CatalogColumn{
			{Name: "activity_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "created_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "data", Type: "jsonb", Nullable: true, Default: ""},
			{Name: "owner_activity_id", Type: "uuid", Nullable: true, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "serialization", Type: "text", Nullable: false, Default: "'json-v1'::text"},
			{Name: "state", Type: "text", Nullable: false, Default: ""},
			{Name: "step", Type: "text", Nullable: true, Default: ""},
		}},
		{Name: "runnerq_worker_pools", PrimaryKey: []string{"pool_id"}, Columns: []CatalogColumn{
			{Name: "activity_types", Type: "_text", Nullable: true, Default: ""},
			{Name: "last_seen_at", Type: "timestamptz", Nullable: false, Default: "now()"},
			{Name: "max_workers", Type: "int4", Nullable: false, Default: ""},
			{Name: "pool_id", Type: "uuid", Nullable: false, Default: ""},
			{Name: "queue_name", Type: "text", Nullable: false, Default: ""},
			{Name: "started_at", Type: "timestamptz", Nullable: false, Default: "now()"},
		}},
	},
	Indexes: []CatalogIndex{
		{Name: "idx_runnerq_activities_processing", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_activities_processing ON runnerq_activities USING btree (queue_name, lease_deadline_ms) WHERE (status = 'processing'::text)"},
		{Name: "idx_runnerq_commands_created", Table: "runnerq_commands", Definition: "CREATE INDEX idx_runnerq_commands_created ON runnerq_commands USING btree (created_at)"},
		{Name: "idx_runnerq_completed_cron", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_completed_cron ON runnerq_activities USING btree (queue_name, completed_at DESC, created_at DESC) WHERE ((status = ANY (ARRAY['completed'::text, 'failed'::text])) AND ((metadata ->> 'source'::text) = 'cron'::text))"},
		{Name: "idx_runnerq_completed_non_cron", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_completed_non_cron ON runnerq_activities USING btree (queue_name, completed_at DESC, created_at DESC) WHERE ((status = ANY (ARRAY['completed'::text, 'failed'::text])) AND ((metadata ->> 'source'::text) IS DISTINCT FROM 'cron'::text))"},
		{Name: "idx_runnerq_dead_letter", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_dead_letter ON runnerq_activities USING btree (queue_name, completed_at DESC) WHERE (status = 'dead_letter'::text)"},
		{Name: "idx_runnerq_dependencies_producer", Table: "runnerq_dependencies", Definition: "CREATE INDEX idx_runnerq_dependencies_producer ON runnerq_dependencies USING btree (queue_name, producer_activity_id)"},
		{Name: "idx_runnerq_dependencies_result", Table: "runnerq_dependencies", Definition: "CREATE INDEX idx_runnerq_dependencies_result ON runnerq_dependencies USING btree (queue_name, result_id)"},
		{Name: "idx_runnerq_dequeue_effective_v2", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_dequeue_effective_v2 ON runnerq_activities USING btree (queue_name, activity_type, priority DESC, retry_count DESC, COALESCE(scheduled_at, created_at)) WHERE (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'retrying'::text, 'waiting'::text]))"},
		{Name: "idx_runnerq_dequeue_order_v2", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_dequeue_order_v2 ON runnerq_activities USING btree (queue_name, priority DESC, retry_count DESC, COALESCE(scheduled_at, created_at)) WHERE (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'retrying'::text, 'waiting'::text]))"},
		{Name: "idx_runnerq_events_activity", Table: "runnerq_events", Definition: "CREATE INDEX idx_runnerq_events_activity ON runnerq_events USING btree (activity_id, created_at DESC)"},
		{Name: "idx_runnerq_events_queue_seq", Table: "runnerq_events", Definition: "CREATE INDEX idx_runnerq_events_queue_seq ON runnerq_events USING btree (queue_name, id)"},
		{Name: "idx_runnerq_parent_id", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_parent_id ON runnerq_activities USING btree (parent_activity_id) WHERE (parent_activity_id IS NOT NULL)"},
		{Name: "idx_runnerq_query_created", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_query_created ON runnerq_activities USING btree (created_at DESC, id DESC)"},
		{Name: "idx_runnerq_query_status_created", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_query_status_created ON runnerq_activities USING btree (status, created_at DESC, id DESC)"},
		{Name: "idx_runnerq_query_type_created", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_query_type_created ON runnerq_activities USING btree (activity_type, created_at DESC, id DESC)"},
		{Name: "idx_runnerq_results_owner", Table: "runnerq_results", Definition: "CREATE INDEX idx_runnerq_results_owner ON runnerq_results USING btree (queue_name, owner_activity_id) WHERE (owner_activity_id IS NOT NULL)"},
		{Name: "idx_runnerq_root_id", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_root_id ON runnerq_activities USING btree (root_activity_id) WHERE (root_activity_id IS NOT NULL)"},
		{Name: "idx_runnerq_root_only", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_root_only ON runnerq_activities USING btree (queue_name, created_at DESC) WHERE (parent_activity_id IS NULL)"},
		{Name: "idx_runnerq_root_status", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_root_status ON runnerq_activities USING btree (queue_name, status) WHERE (parent_activity_id IS NULL)"},
		{Name: "idx_runnerq_root_terminal_age", Table: "runnerq_activities", Definition: "CREATE INDEX idx_runnerq_root_terminal_age ON runnerq_activities USING btree (queue_name, status, completed_at) WHERE ((parent_activity_id IS NULL) AND (status = ANY (ARRAY['completed'::text, 'failed'::text, 'dead_letter'::text])))"},
		{Name: "idx_runnerq_worker_pools_queue_alive", Table: "runnerq_worker_pools", Definition: "CREATE INDEX idx_runnerq_worker_pools_queue_alive ON runnerq_worker_pools USING btree (queue_name, last_seen_at)"},
	},
	RetiredColumns: []string{"runnerq_activities.payload"},
	RetiredIndexes: []string{"idx_runnerq_dequeue_effective", "idx_runnerq_dequeue_order"},
}
