// Code generated by runnerq-spec tools/gen from protocol/conductor/conductor.schema.json. DO NOT EDIT.

package wire

import (
	"encoding/json"
)

// Version is the protocol version these types are.
const Version = 1

// Message types.
const (
	// The first frame, within 10 seconds of connecting.
	TypeHello               = "hello"
	TypeGoodbye             = "goodbye"
	TypeActivitiesList      = "activities.list"
	TypeActivitiesGet       = "activities.get"
	TypeActivitiesCount     = "activities.count"
	TypeActivitiesAggregate = "activities.aggregate"
	TypeStepsList           = "steps.list"
	// Over events; sorted by at.
	TypeEventsList            = "events.list"
	TypeResultsGet            = "results.get"
	TypeTreesGet              = "trees.get"
	TypeExecutorDescribe      = "executor.describe"
	TypeActivitiesCancel      = "activities.cancel"
	TypeActivitiesRetry       = "activities.retry"
	TypeActivitiesRunNow      = "activities.run_now"
	TypeActivitiesReschedule  = "activities.reschedule"
	TypeActivitiesSetPriority = "activities.set_priority"
	TypeActivitiesDelete      = "activities.delete"
	TypeActivitiesSignal      = "activities.signal"
	TypeEventsSubscribe       = "events.subscribe"
	TypeEventsUnsubscribe     = "events.unsubscribe"
	TypeStreamEvents          = "stream.events"
	TypeStreamGap             = "stream.gap"
	// Every config.report_interval_ms, without running.
	TypeExecutorReport = "executor.report"
	// Only while config.notices is on; at most every 250 ms.
	TypeActivityNotices = "activity.notices"
	// The fields that change; the agent applies them at once.
	TypeConfigUpdate = "config.update"
)

// Kind is what an envelope is: a request, its response, or an event.
type Kind string

const (
	KindRequest  Kind = "req"
	KindResponse Kind = "res"
	KindEvent    Kind = "evt"
)

// ErrorCode is a failure class. Agents reject anything they don't understand
// with unsupported.
type ErrorCode string

const (
	CodeInvalidArgument    ErrorCode = "invalid_argument"
	CodeNotFound           ErrorCode = "not_found"
	CodeFailedPrecondition ErrorCode = "failed_precondition"
	CodeConflict           ErrorCode = "conflict"
	CodeForbidden          ErrorCode = "forbidden"
	CodeUnsupported        ErrorCode = "unsupported"
	CodeResourceExhausted  ErrorCode = "resource_exhausted"
	CodeDeadlineExceeded   ErrorCode = "deadline_exceeded"
	CodeUnavailable        ErrorCode = "unavailable"
	CodeInternal           ErrorCode = "internal"
)

// TargetKind is how a command can select its activities.
type TargetKind string

const (
	TargetIDs            TargetKind = "ids"
	TargetFilter         TargetKind = "filter"
	TargetIdempotencyKey TargetKind = "idempotency_key"
)

// DataMode is what an agent may send: full, or metadata_only (no payloads,
// results, error messages or event details).
type DataMode string

const (
	DataModeFull         DataMode = "full"
	DataModeMetadataOnly DataMode = "metadata_only"
)

// FilterOp is a filter predicate's operator; contains needs the text
// capability.
type FilterOp string

const (
	OpEq       FilterOp = "eq"
	OpNe       FilterOp = "ne"
	OpIn       FilterOp = "in"
	OpNin      FilterOp = "nin"
	OpLt       FilterOp = "lt"
	OpLte      FilterOp = "lte"
	OpGt       FilterOp = "gt"
	OpGte      FilterOp = "gte"
	OpExists   FilterOp = "exists"
	OpPrefix   FilterOp = "prefix"
	OpContains FilterOp = "contains"
)

// SortOrder is sort direction.
type SortOrder string

const (
	OrderAsc  SortOrder = "asc"
	OrderDesc SortOrder = "desc"
)

// MetricName is an aggregate measure.
type MetricName string

const (
	MetricCount    MetricName = "count"
	MetricDuration MetricName = "duration"
)

// DurationField is which duration: queue, from created or scheduled to the
// first start; run, from the last attempt's start to completion; total, from
// created to completion.
type DurationField string

const (
	DurationQueue DurationField = "queue"
	DurationRun   DurationField = "run"
	DurationTotal DurationField = "total"
)

// ActivityStatus is a canonical status. A retry is scheduled with attempt
// above 1; there is no retrying status.
type ActivityStatus string

const (
	StatusPending    ActivityStatus = "pending"
	StatusScheduled  ActivityStatus = "scheduled"
	StatusRunning    ActivityStatus = "running"
	StatusWaiting    ActivityStatus = "waiting"
	StatusCompleted  ActivityStatus = "completed"
	StatusFailed     ActivityStatus = "failed"
	StatusDeadLetter ActivityStatus = "dead_letter"
	StatusCancelled  ActivityStatus = "cancelled"
)

// ResultState is an outcome.
type ResultState string

const (
	ResultOK    ResultState = "ok"
	ResultError ResultState = "error"
)

// WaitKind is what a waiting activity is parked on.
type WaitKind string

const (
	WaitSleep    WaitKind = "sleep"
	WaitSignal   WaitKind = "signal"
	WaitChildren WaitKind = "children"
	WaitOther    WaitKind = "other"
)

// StepKind is what a step is.
type StepKind string

const (
	StepRun    StepKind = "run"
	StepSleep  StepKind = "sleep"
	StepSignal StepKind = "signal"
	StepChild  StepKind = "child"
	StepOther  StepKind = "other"
)

// CancelCascade is how far a cancel reaches: children (the default) also
// cancels non-terminal descendants, none only the targets.
type CancelCascade string

const (
	CascadeChildren CancelCascade = "children"
	CascadeNone     CancelCascade = "none"
)

// DeleteCascade is how far a delete reaches: tree, the only cascade and the
// default, removes a finished root with its whole tree.
type DeleteCascade string

const (
	CascadeTree DeleteCascade = "tree"
)

// CommandOutcome is what happened to one target; would_apply on dry runs.
type CommandOutcome string

const (
	OutcomeApplied    CommandOutcome = "applied"
	OutcomeSkipped    CommandOutcome = "skipped"
	OutcomeWouldApply CommandOutcome = "would_apply"
)

// NoticeType is a lifecycle change no event is stored for: the activity's own
// times say it.
type NoticeType string

const (
	NoticeCreated          NoticeType = "activity.created"
	NoticeScheduled        NoticeType = "activity.scheduled"
	NoticeAttemptStarted   NoticeType = "attempt.started"
	NoticeAttemptSucceeded NoticeType = "attempt.succeeded"
)

// Envelope is one frame on the wire: one JSON object per WebSocket text frame.
type Envelope struct {
	// The protocol version the sender speaks; 1.
	V    int  `json:"v"`
	Kind Kind `json:"kind"`
	// Set on requests and echoed by their response.
	ID string `json:"id,omitempty"`
	// The message type, e.g. activities.list; a response echoes its request's.
	Type string `json:"type"`
	// The message's data (see x-messages); absent with error.
	Data json.RawMessage `json:"data,omitempty"`
	// Replaces data in a failed response.
	Error *Error `json:"error,omitempty"`
	Meta  *Meta  `json:"meta,omitempty"`
}

// Meta is out-of-band fields; receivers ignore keys they don't know.
type Meta struct {
	// When the sender stops waiting for the response.
	Deadline string `json:"deadline,omitempty"`
	// The message version, when above 1.
	Mv int `json:"mv,omitempty"`
	// W3C trace context.
	Traceparent string `json:"traceparent,omitempty"`
}

// Error is a failed response, or a failed item in a command result.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
	// invalid_argument and unsupported name the input as field;
	// failed_precondition gives the activity's status.
	Details map[string]any `json:"details,omitempty"`
}

// SDKInfo is the agent's SDK.
type SDKInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	// go, typescript, ...
	Language string `json:"language"`
}

// ExecutorInfo is the worker process behind a session.
type ExecutorInfo struct {
	// Stable for the process; a newer session with the same id supersedes an
	// older one.
	ID             string            `json:"id"`
	Hostname       string            `json:"hostname,omitempty"`
	Queues         []string          `json:"queues,omitempty"`
	ActivityTypes  []string          `json:"activity_types,omitempty"`
	MaxConcurrency int               `json:"max_concurrency,omitempty"`
	StartedAt      string            `json:"started_at,omitempty"`
	Labels         map[string]string `json:"labels,omitempty"`
}

// Capability is one message type an agent serves, and the sub-features it
// supports; only the lists relevant to the message are set.
type Capability struct {
	// The message's version.
	V       int      `json:"v"`
	Filters []string `json:"filters,omitempty"`
	Sorts   []string `json:"sorts,omitempty"`
	Include []string `json:"include,omitempty"`
	GroupBy []string `json:"group_by,omitempty"`
	Buckets []string `json:"buckets,omitempty"`
	// count, and duration.<field> for each duration field.
	Metrics []string     `json:"metrics,omitempty"`
	Targets []TargetKind `json:"targets,omitempty"`
}

// Limits is one side's limits; the effective limit is the smaller of the two.
type Limits struct {
	MaxFrameBytes         int `json:"max_frame_bytes,omitempty"`
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty"`
}

// Hello is the agent's handshake, its first frame.
type Hello struct {
	// Versions the agent speaks; the gateway picks the highest both do.
	ProtocolVersions []int        `json:"protocol_versions"`
	SDK              SDKInfo      `json:"sdk"`
	Executor         ExecutorInfo `json:"executor"`
	// Keyed by message type.
	Capabilities map[string]Capability `json:"capabilities"`
	Limits       Limits                `json:"limits"`
}

// AppRef is the app a session belongs to.
type AppRef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// SessionConfig is the gateway's settings for a session; config.update carries
// the fields that change.
type SessionConfig struct {
	DataMode DataMode `json:"data_mode,omitempty"`
	// How often to send executor.report.
	ReportIntervalMS int64 `json:"report_interval_ms,omitempty"`
	// Send activity.notices. The gateway turns it on while someone is watching
	// the app and off when no one is. Absent in a welcome is off; absent in a
	// config.update is unchanged.
	Notices *bool `json:"notices,omitempty"`
}

// Welcome is the gateway's answer to hello.
type Welcome struct {
	Version   int           `json:"version"`
	SessionID string        `json:"session_id"`
	App       AppRef        `json:"app"`
	Config    SessionConfig `json:"config"`
	Limits    Limits        `json:"limits"`
}

// Goodbye is sent by an agent before a graceful shutdown.
type Goodbye struct {
	Reason string `json:"reason"`
}

// Filter is a boolean expression over a resource's fields: exactly one of the
// combinators (and, or, not) or a predicate (field, op, value).
type Filter struct {
	And []Filter `json:"and,omitempty"`
	Or  []Filter `json:"or,omitempty"`
	Not *Filter  `json:"not,omitempty"`
	// A dotted path into the resource; metadata.<key> addresses a metadata tag.
	Field string   `json:"field,omitempty"`
	Op    FilterOp `json:"op,omitempty"`
	// The operand: a list for in and nin, absent for exists.
	Value json.RawMessage `json:"value,omitempty"`
}

// Sort is one ordering of a query, by an advertised field; agents add the id
// as a tiebreaker.
type Sort struct {
	Field string `json:"field"`
	// Default desc.
	Order SortOrder `json:"order,omitempty"`
}

// Query is the common list request.
type Query struct {
	Filter *Filter `json:"filter,omitempty"`
	Sort   []Sort  `json:"sort,omitempty"`
	// Heavy fields to return: payload, result, last_error.
	Include []string `json:"include,omitempty"`
	// Default 50.
	Limit int `json:"limit,omitempty"`
	// From the previous page's next_cursor.
	Cursor string `json:"cursor,omitempty"`
}

// ActivityPage is a page of activities.
type ActivityPage struct {
	Items []Activity `json:"items"`
	// Present when more items exist.
	NextCursor string `json:"next_cursor,omitempty"`
}

// StepPage is a page of steps.
type StepPage struct {
	Items []Step `json:"items"`
	// Present when more items exist.
	NextCursor string `json:"next_cursor,omitempty"`
}

// EventPage is a page of events.
type EventPage struct {
	Items []Event `json:"items"`
	// Present when more items exist.
	NextCursor string `json:"next_cursor,omitempty"`
}

// GetRequest is a request for one activity.
type GetRequest struct {
	ID string `json:"id"`
	// payload, result, last_error, steps, events.
	Include []string `json:"include,omitempty"`
}

// CountRequest is a request to count the activities matching a filter.
type CountRequest struct {
	Filter *Filter `json:"filter,omitempty"`
}

// CountResult is a count; over large sets an agent may estimate, and say so.
type CountResult struct {
	Count int64 `json:"count"`
	Exact bool  `json:"exact"`
}

// StepsRequest is a request for an activity's steps.
type StepsRequest struct {
	ActivityID string `json:"activity_id"`
	// result.
	Include []string `json:"include,omitempty"`
	Limit   int      `json:"limit,omitempty"`
	Cursor  string   `json:"cursor,omitempty"`
}

// ResultRequest is a request for an activity's result.
type ResultRequest struct {
	ActivityID string `json:"activity_id"`
}

// TreeRequest is a request for the tree an activity belongs to; id may be any
// activity in it.
type TreeRequest struct {
	ID       string   `json:"id"`
	Include  []string `json:"include,omitempty"`
	MaxNodes int      `json:"max_nodes,omitempty"`
}

// Tree is an activity tree.
type Tree struct {
	RootID    string     `json:"root_id"`
	Items     []Activity `json:"items"`
	Truncated bool       `json:"truncated"`
}

// Bucket is the time buckets an aggregate is split into.
type Bucket struct {
	// An advertised time field, e.g. completed_at.
	Field      string `json:"field"`
	IntervalMS int64  `json:"interval_ms"`
	From       string `json:"from,omitempty"`
	To         string `json:"to,omitempty"`
}

// Metric is one aggregate measure.
type Metric struct {
	Name MetricName `json:"name"`
	// For duration.
	Field       DurationField `json:"field,omitempty"`
	Percentiles []float64     `json:"percentiles,omitempty"`
}

// AggregateRequest is a request to group and measure activities.
type AggregateRequest struct {
	Filter  *Filter  `json:"filter,omitempty"`
	GroupBy []string `json:"group_by,omitempty"`
	Bucket  *Bucket  `json:"bucket,omitempty"`
	Metrics []Metric `json:"metrics"`
	Limit   int      `json:"limit,omitempty"`
}

// AggregateGroup is one group of an aggregate.
type AggregateGroup struct {
	// The group_by fields' values.
	Key map[string]string `json:"key,omitempty"`
	// The bucket's start.
	Bucket string `json:"bucket,omitempty"`
	Count  *int64 `json:"count,omitempty"`
	// Duration field (run) to percentile (p95) to milliseconds.
	Durations map[string]map[string]float64 `json:"durations,omitempty"`
}

// AggregateResult is an aggregate's groups.
type AggregateResult struct {
	Groups    []AggregateGroup `json:"groups"`
	Truncated bool             `json:"truncated"`
}

// ErrorInfo is a failure.
type ErrorInfo struct {
	// Omitted in metadata-only mode.
	Message string `json:"message,omitempty"`
	// retryable, non_retryable, timeout, ...
	Kind string `json:"kind,omitempty"`
	At   string `json:"at,omitempty"`
}

// Result is an activity's or step's outcome: data when ok, error when not.
type Result struct {
	State ResultState     `json:"state"`
	Data  json.RawMessage `json:"data,omitempty"`
	Error *ErrorInfo      `json:"error,omitempty"`
}

// Wait is why a waiting activity is parked.
type Wait struct {
	Kind  WaitKind `json:"kind"`
	Name  string   `json:"name,omitempty"`
	Until string   `json:"until,omitempty"`
}

// Activity is an activity. Fields that don't apply are omitted, not null.
type Activity struct {
	ID     string         `json:"id"`
	Type   string         `json:"type"`
	Queue  string         `json:"queue,omitempty"`
	Status ActivityStatus `json:"status"`
	// 1 low to 4 critical.
	Priority       int    `json:"priority"`
	RootID         string `json:"root_id,omitempty"`
	ParentID       string `json:"parent_id,omitempty"`
	Depth          int    `json:"depth"`
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// The current or last attempt, from 1.
	Attempt int `json:"attempt"`
	// Absent when unlimited.
	MaxAttempts    int    `json:"max_attempts,omitempty"`
	CreatedAt      string `json:"created_at"`
	ScheduledFor   string `json:"scheduled_for,omitempty"`
	StartedAt      string `json:"started_at,omitempty"`
	CompletedAt    string `json:"completed_at,omitempty"`
	UpdatedAt      string `json:"updated_at,omitempty"`
	TimeoutMS      int64  `json:"timeout_ms,omitempty"`
	LeaseExpiresAt string `json:"lease_expires_at,omitempty"`
	// The executor running it, while running.
	ExecutorID string `json:"executor_id,omitempty"`
	// While waiting.
	Wait     *Wait             `json:"wait,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	// When included.
	LastError *ErrorInfo `json:"last_error,omitempty"`
	// When included; never in metadata-only mode.
	Payload json.RawMessage `json:"payload,omitempty"`
	// When included; never in metadata-only mode.
	Result *Result `json:"result,omitempty"`
	// When included on activities.get; an included empty list is [].
	Steps *[]Step `json:"steps,omitempty"`
	// When included on activities.get; an included empty list is [].
	Events *[]Event `json:"events,omitempty"`
	// SDK-specific data keyed by SDK language; the Cloud may show it but never
	// depends on it.
	Extensions map[string]json.RawMessage `json:"extensions,omitempty"`
}

// Step is a durable checkpoint inside an activity.
type Step struct {
	ID         string   `json:"id"`
	ActivityID string   `json:"activity_id"`
	Name       string   `json:"name"`
	Kind       StepKind `json:"kind"`
	// completed or failed, from its result.
	Status      ActivityStatus `json:"status"`
	CreatedAt   string         `json:"created_at"`
	CompletedAt string         `json:"completed_at,omitempty"`
	// When the step spawned a child.
	ChildID string `json:"child_id,omitempty"`
	// When included.
	Result *Result `json:"result,omitempty"`
}

// Event is an entry in an activity's history.
type Event struct {
	// Unique; consumers drop repeats by it.
	ID string `json:"id"`
	// Ordered, shared across the app's executors.
	Cursor     string `json:"cursor"`
	ActivityID string `json:"activity_id"`
	// A group and name: activity.created, attempt.started, ... Unknown types are
	// shown generically.
	Type       string `json:"type"`
	At         string `json:"at"`
	ExecutorID string `json:"executor_id,omitempty"`
	Attempt    int    `json:"attempt,omitempty"`
	// Open; omitted in metadata-only mode.
	Detail json.RawMessage `json:"detail,omitempty"`
}

// RunningActivity is an activity in flight on an executor.
type RunningActivity struct {
	ActivityID string `json:"activity_id"`
	Type       string `json:"type"`
	Attempt    int    `json:"attempt"`
	StartedAt  string `json:"started_at"`
}

// ExecutorCounters is the counts of an executor's activity outcomes since it
// started.
type ExecutorCounters struct {
	Claimed      int64 `json:"claimed"`
	Succeeded    int64 `json:"succeeded"`
	Retried      int64 `json:"retried"`
	Failed       int64 `json:"failed"`
	TimedOut     int64 `json:"timed_out"`
	DeadLettered int64 `json:"dead_lettered"`
	ClaimsLost   int64 `json:"claims_lost"`
}

// ExecutorState is an executor's live, in-memory state: executor.describe's
// answer, and (without running) executor.report's data.
type ExecutorState struct {
	ID             string `json:"id"`
	UptimeMS       int64  `json:"uptime_ms"`
	MaxConcurrency int    `json:"max_concurrency"`
	InFlight       int    `json:"in_flight"`
	// On executor.describe and hosted reports, [] when nothing runs; omitted from
	// executor.report.
	Running *[]RunningActivity `json:"running,omitempty"`
	// How long the latest activity waited to start after it was due.
	ClaimLagMS        int64            `json:"claim_lag_ms"`
	HeartbeatFailures int64            `json:"heartbeat_failures"`
	Draining          bool             `json:"draining"`
	Counters          ExecutorCounters `json:"counters"`
}

// ExecutorReport is a hosted worker's heartbeat to the data plane (PUT
// /v1/executors/{id}, with the store key; see the storage protocol): its
// hello's sdk and executor, and its state with running.
type ExecutorReport struct {
	SDK      SDKInfo       `json:"sdk"`
	Executor ExecutorInfo  `json:"executor"`
	State    ExecutorState `json:"state"`
}

// Empty is the data of a message that has none.
type Empty struct{}

// Target is what a command acts on: ids, a filter bounded by max, or an
// idempotency key and type (signals).
type Target struct {
	IDs            []string `json:"ids,omitempty"`
	IdempotencyKey string   `json:"idempotency_key,omitempty"`
	Type           string   `json:"type,omitempty"`
	Filter         *Filter  `json:"filter,omitempty"`
	// Required with filter.
	Max int `json:"max,omitempty"`
	// Set by the Cloud: the queue the routed executor serves. A mismatch is
	// failed_precondition.
	Queue string `json:"queue,omitempty"`
}

// CancelRequest is the request of activities.cancel, which cancels
// non-terminal activities. Each command accepts only its own fields.
type CancelRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason  string        `json:"reason,omitempty"`
	Cascade CancelCascade `json:"cascade,omitempty"`
}

// RetryRequest is the request of activities.retry, which runs failed,
// dead-lettered or cancelled activities again, keeping their checkpoints. Each
// command accepts only its own fields.
type RetryRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason        string `json:"reason,omitempty"`
	ResetAttempts bool   `json:"reset_attempts,omitempty"`
}

// RunNowRequest is the request of activities.run_now, which makes scheduled or
// waiting activities runnable now. Each command accepts only its own fields.
type RunNowRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason string `json:"reason,omitempty"`
}

// RescheduleRequest is the request of activities.reschedule, which moves a
// scheduled activity's time. Each command accepts only its own fields.
type RescheduleRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason string `json:"reason,omitempty"`
	At     string `json:"at"`
}

// SetPriorityRequest is the request of activities.set_priority, which changes
// non-terminal activities' priority. Each command accepts only its own fields.
type SetPriorityRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason   string `json:"reason,omitempty"`
	Priority int    `json:"priority"`
}

// DeleteRequest is the request of activities.delete, which deletes finished
// roots with their trees and history. Each command accepts only its own
// fields.
type DeleteRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason  string        `json:"reason,omitempty"`
	Cascade DeleteCascade `json:"cascade,omitempty"`
}

// SignalRequest is the request of activities.signal, which delivers a signal,
// waking the activity if it waits. Each command accepts only its own fields.
type SignalRequest struct {
	// Makes the command idempotent: the same id replays the stored outcome; with
	// different input it is a conflict. The Cloud always sends one; without it
	// nothing is recorded or replayed.
	CommandID string `json:"command_id,omitempty"`
	Target    Target `json:"target"`
	// Say what would happen, changing nothing.
	DryRun bool `json:"dry_run,omitempty"`
	// Recorded in the activity's history.
	Reason  string          `json:"reason,omitempty"`
	Name    string          `json:"name"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// CommandItem is the result for one target.
type CommandItem struct {
	ID      string         `json:"id"`
	Outcome CommandOutcome `json:"outcome"`
	Status  ActivityStatus `json:"status,omitempty"`
	Error   *Error         `json:"error,omitempty"`
}

// CommandResult is a command's outcome. Per-item failures don't fail the
// request; a request-level error means nothing was applied.
type CommandResult struct {
	Matched int `json:"matched"`
	Applied int `json:"applied"`
	// Descendants a cascading cancel also cancelled.
	Cascaded int `json:"cascaded,omitempty"`
	// A bounded filter target left more to act on.
	More bool `json:"more"`
	// Served from the command ledger.
	Replayed bool          `json:"replayed,omitempty"`
	Results  []CommandItem `json:"results"`
}

// EventsSubscribe is a request to start an event stream; without after_cursor
// it starts at the end of the log.
type EventsSubscribe struct {
	Filter      *Filter `json:"filter,omitempty"`
	AfterCursor string  `json:"after_cursor,omitempty"`
	MaxBatch    int     `json:"max_batch,omitempty"`
	MaxDelayMS  int     `json:"max_delay_ms,omitempty"`
}

// Subscription is a subscription and where it starts.
type Subscription struct {
	SubscriptionID string `json:"subscription_id"`
	// Absent when the log is empty.
	Cursor string `json:"cursor,omitempty"`
}

// EventsUnsubscribe is a request to end a subscription.
type EventsUnsubscribe struct {
	SubscriptionID string `json:"subscription_id"`
}

// StreamEvents is a batch of a subscription's events; cursor is where to
// resume.
type StreamEvents struct {
	SubscriptionID string  `json:"subscription_id"`
	Items          []Event `json:"items"`
	Cursor         string  `json:"cursor"`
}

// StreamGap is a notice that events after since_cursor may have been lost;
// re-query them with events.list.
type StreamGap struct {
	SubscriptionID string `json:"subscription_id"`
	SinceCursor    string `json:"since_cursor"`
}

// Notice is a lifecycle change an executor made, announced live. Never stored
// and never resent: it has no cursor, and a consumer that missed it reads the
// activity instead.
type Notice struct {
	ActivityID   string     `json:"activity_id"`
	Type         NoticeType `json:"type"`
	At           string     `json:"at"`
	Queue        string     `json:"queue"`
	ActivityType string     `json:"activity_type"`
	// The activity's workflow root; the activity's own id for a root.
	RootID string `json:"root_id"`
	// For attempt.started and attempt.succeeded.
	Attempt int `json:"attempt,omitempty"`
	// The executor that made the change, when it was one.
	ExecutorID string `json:"executor_id,omitempty"`
}

// ActivityNotices is a batch of notices, oldest first.
type ActivityNotices struct {
	Items []Notice `json:"items"`
	// Notices this agent discarded since its last batch, when it produced them
	// faster than it could send.
	Dropped int64 `json:"dropped,omitempty"`
}
